# Generated by Django 2.0 on 2018-01-18 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PORevisions',
            new_name='PORevision',
        ),
        migrations.RenameModel(
            old_name='PurchaseOrders',
            new_name='PurchaseOrder',
        ),
        migrations.AlterModelOptions(
            name='invoicestatus',
            options={'verbose_name': 'Invoice Status', 'verbose_name_plural': 'Invoice Statuses'},
        ),
        migrations.AlterModelOptions(
            name='porevision',
            options={'verbose_name': 'PO Revision'},
        ),
        migrations.AlterModelOptions(
            name='purchaseorder',
            options={'verbose_name': 'Purchase Order'},
        ),
    ]
